# image: docker:19.03.12

# services:
#   - docker:19.03.12-dind

stages:
  - build
  - deploy

variables:
  DEPLOY_DIR: '/www/egg-vue'
  BUILD_PATH: './public'
  APP_PACKAGE_NAME: 'package'
  PACKAGE_MD5: '/package/md5'

  # When using dind service, we need to instruct docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket. Docker 19.03 does this automatically
  # by setting the DOCKER_HOST in
  # https://github.com/docker-library/docker/blob/d45051476babc297257df490d22cbd806f1b11e4/19.03/docker-entrypoint.sh#L23-L29
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services.
  #
  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: '/certs'

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - docker info

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build: # jobs
  image: node:14.15.3-alpine3.12
  stage: build
  only: # 定义在特定的分支上执行该jobs
    - main
  before_script:
    - echo "Before script in build stage that overwrited the globally defined before_script"
  after_script:
    - echo "After script in build stage that overwrited the globally defined after_script"
  cache: # 配置缓存文件夹
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts: # 将这个job生成的依赖传递给下一个job, 需要配置dependencies
    expire_in: 60 mins # 设置过期时间，过期后依赖的数据将会被删除
    paths: # 需要传递给下一个job的目录
      - node_modules/
  script:
    - echo "========== start install package =========="
    - npm install --registry=https://registry.npm.taobao.org/
    - echo "========== after install package =========="
    - echo "========== start build =========="
    - npm run build
    - echo "========== after build =========="
    - mkdir -p $DEPLOY_DIR
    - mv $BUILD_PATH/* $DEPLOY_DIR
    - tar zcf $APP_PACKAGE_NAME $DEPLOY_DIR
    - mkdir -p $PACKAGE_MD5
    - md5sum $APP_PACKAGE_NAME
  tags:
    - egg-vue
  when: manual

deploy: # jobs
  stage: deploy
  only:
    - main
  script:
    - echo "========== start deploy =========="
    - docker build -t egg-vue .
    - docker run -dit -p 7001:7002 egg-vue
    # - npm run deploy
